# -*- coding: utf-8 -*-

module LaTeX
  module Decode
    
    class Symbols < Decoder
      @map = Hash[*%W{
        textcolonmonetary \u20A1
        textlira          \u20A4
        textnaira         \u20A6
        textwon           \u20A9
        textdong          \u20AB
        euro              \u20AC
        texteuro          \u20AC
        textnumero        \u2116
        texttrademark     \u2122
        leftarrow         \u2190
        uparrow           \u2191
        rightarrow        \u2192
        downarrow         \u2193
        leftrightarrow    \u2194
        updownarrow       \u2195
        leadsto           \u219D
        rightleftharpoons \u21CC
        Rightarrow        \u21D2
        Leftrightarrow    \u21D4
        forall            \u2200
        complement        \u2201
        partial           \u2202
        exists            \u2203
        nexists           \u2204
        set               \u2205
        Delta             \u2206
        nabla             \u2207
        in                \u2208
        notin             \u2209
        ni                \u220B
        prod              \u220F
        coprod            \u2210
        sum               \u2211
        mp                \u2213
        dotplus           \u2214
        setminus          \u2216
        ast               \u2217
        circ              \u2218
        bullet            \u2219
        surd              \u221A
        propto            \u221D
        infty             \u221E
        angle             \u2220
        measuredangle     \u2221
        sphericalangle    \u2222
        mid               \u2223
        nmid              \u2224
        parallel          \u2225
        nparallel         \u2226
        wedge             \u2227
        vee               \u2228
        cap               \u2229
        cup               \u222A
        int               \u222B
        iint              \u222C
        iiint             \u222D
        oint              \u222E
        therefore         \u2234
        because           \u2235
        sim               \u223C
        backsim           \u223D
        wr                \u2240
        nsim              \u2241
        simeq             \u2243
        cong              \u2245
        ncong             \u2247
        approx            \u2248
        approxeq          \u224A
        asymp             \u224D
        Bumpeq            \u224E
        bumpeq            \u224F
        doteq             \u2250
        doteqdot          \u2251
        fallingdotseq     \u2252
        risingdotseq      \u2253
        eqcirc            \u2256
        circeq            \u2257
        triangleq         \u225C
        neq               \u2260
        equiv             \u2261
        leq               \u2264
        geq               \u2265
        leqq              \u2266
        geqq              \u2267
        lneqq             \u2268
        gneqq             \u2269
        ll                \u226A
        gg                \u226B
        between           \u226C
        nless             \u226E
        ngtr              \u226F
        nleq              \u2270
        ngeq              \u2271
        lesssim           \u2272
        gtrsim            \u2273
        lessgtr           \u2276
        gtrless           \u2277
        prec              \u227A
        succ              \u227B
        preccurlyeq       \u227C
        succcurlyeq       \u227D
        precsim           \u227E
        succsim           \u227F
        nprec             \u2280
        nsucc             \u2281
        subset            \u2282
        supset            \u2283
        subseteq          \u2286
        supseteq          \u2287
        nsubseteq         \u2288
        nsupseteq         \u2289
        subsetneq         \u228A
        supsetneq         \u228B
        uplus             \u228E
        sqsubset          \u228F
        sqsupset          \u2290
        sqsubseteq        \u2291
        sqsupseteq        \u2292
        sqcap             \u2293
        sqcup             \u2294
        oplus             \u2295
        ominus            \u2296
        otimes            \u2297
        oslash            \u2298
        odot              \u2299
        circledcirc       \u229A
        circledast        \u229B
        circleddash       \u229D
        boxplus           \u229E
        boxminus          \u229F
        boxtimes          \u22A0
        boxdot            \u22A1
        vdash             \u22A2
        dashv             \u22A3
        top               \u22A4
        bot               \u22A5
        Vdash             \u22A9
        Vvdash            \u22AA
        nVdash            \u22AE
        lhd               \u22B2
        rhd               \u22B3
        unlhd             \u22B4
        unrhd             \u22B5
        multimap          \u22B8
        intercal          \u22BA
        veebar            \u22BB
        barwedge          \u22BC
        bigwedge          \u22C0
        bigvee            \u22C1
        bigcap            \u22C2
        bigcup            \u22C3
        diamond           \u22C4
        cdot              \u22C5
        star              \u22C6
        divideontimes     \u22C7
        bowtie            \u22C8
        ltimes            \u22C9
        rtimes            \u22CA
        leftthreetimes    \u22CB
        rightthreetimes   \u22CC
        backsimeq         \u22CD
        curlyvee          \u22CE
        curlywedge        \u22CF
        Subset            \u22D0
        Supset            \u22D1
        Cap               \u22D2
        Cup               \u22D3
        pitchfork         \u22D4
        lessdot           \u22D6
        gtrdot            \u22D7
        lll               \u22D8
        ggg               \u22D9
        lesseqgtr         \u22DA
        gtreqless         \u22DB
        curlyeqprec       \u22DE
        curlyeqsucc       \u22DF
        lnsim             \u22E6
        gnsim             \u22E7
        precnsim          \u22E8
        succnsim          \u22E9
        ntriangleleft     \u22EA
        ntriangleright    \u22EB
        ntrianglelefteq   \u22EC
        ntrianglerighteq  \u22ED
        vdots             \u22EE
        cdots             \u22EF
        ddots             \u22F1
        lceil             \u2308
        rceil             \u2309
        lfloor            \u230A
        rfloor            \u230B
        Box               \u25A1
        spadesuit         \u2660
        heartsuit         \u2661
        diamondsuit       \u2662
        clubsuit          \u2663
        flat              \u266D
        natural           \u266E
        sharp             \u266F
        tone5             \u02E5
        tone4             \u02E6
        tone3             \u02E7
        tone2             \u02E8
        tone1             \u02E9
        ss                ß
      }].freeze

      @patterns = [
        /\\(#{ map.keys.map { |k| Regexp.escape(k) }.join('|') })(?:\{\}|\s+|\b)/ou
      ].freeze
      
    end

  end
end